name: "ssm"
version: "dev"
usage: "Inject AWS SSM parameters into Helm values files"
description: |-
  Inject AWS SSM parameters into Helm values files
ignoreFlags: false
useTunnel: false
command: "$HELM_PLUGIN_DIR/helm-ssm"
hooks:
  install: "$HELM_PLUGIN_DIR/install-binary.sh"
  update: "$HELM_PLUGIN_DIR/install-binary.sh"
