name: Release Helm SSM

on:
  push:
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Version
        run: |
          echo ${GITHUB_REF#refs/*/} > .version
      - name: Test project
        run: |
          mkdir -p $TEST_RESULTS
          go get github.com/jstemmer/go-junit-report
          make test | go-junit-report >> ${TEST_RESULTS}/go-test-report.xml
        env:
          TEST_RESULTS: ./helm-ssm
      - name: Build
        run: make dist
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./_dist/*.tgz
